name: front_v1
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  font_awesome_flutter: ^8.5.0
  flare_splash_screen: ^2.0.1+2
  simple_animations: ^1.3.3
  http: any
  shared_preferences: any
  rounded_loading_button: ^1.0.0
  custom_radio: ^0.1.2
  fluttertoast: ^4.0.0
  google_maps_flutter: ^0.5.26+4
  json_serializable: ^2.0.2
  animated_qr_code_scanner:
    git:
      url: https://github.com/kiatuki/animated_qr_code_scanner.git
      ref: v0.1.7

  # Time format
  intl: ^0.15.8
  sliding_up_panel: ^1.0.2
  google_fonts:
  fl_chart: ^0.9.4
  folding_cell: "^0.1.2"
  polygon_clipper: ^1.0.2


  flutter_polyline_points: ^0.1.0
  google_map_polyline:
  permission:
  flutter_custom_dialog: ^1.0.19
  geocoder: ^0.2.1
  lite_rolling_switch: ^0.1.1
  dynamic_theme: ^1.0.0
  firebase_messaging:
  vibrate: ^0.0.4

  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  charts_flutter: ^0.9.0
  flutter_dialogflow: ^0.1.2
  flushbar:
  giffy_dialog:


  flutter_socket_plugin: ^1.0.1
  web_socket_channel: ^1.1.0



flutter_icons:
  image_path_android: "assets/images/logo/logoyepyou.png"
  image_path_ios: "assets/images/logo/logoyepyou.png"
  android: true
  ios: true

flutter_launcher_name:
  name: "YepYou"


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onedevice/
    - assets/images/Dashboard/
    - assets/images/Device/
    - assets/images/login/
    - assets/images/navbar/
    - assets/images/SlpashScreen/
    - assets/images/map/
    - assets/images/logo/
    - assets/images/user/

    - assets/splashscreen.flr
    - splashscreen.flr
    - assets/pfe-project-notif-4d6ee945e624.json




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
